app:
  name: "The Brain"
  environment: "development"
  model_dir: "/workspace/models"
  data_dir: "/workspace/data"
  log_dir: "/workspace/logs"
orchestrator:
  max_depth: 3
  evaluation_threshold: 0.6
memory:
  database_path: "data/brain.db"
  embedding_dim: 128
actions:
  sandbox_dir: "sandbox"
safety:
  require_human_approval: true
  allowed_domains:
    - "example.com"
    - "localhost"
