runtime:
  offline_mode: true
  enforcement_version: "1.0.0"
  constitution_path: "laws/constitution.yaml"
  logs_dir: "logs"
  reflections_dir: "logs/reflections"
  sandbox_root: "sandbox/agents"
  proposal_dir: "scriptSuggestions"
  db_path: "memory/data/state.db"
  ledger_path: "memory/data/ledger.db"
  max_runtime_seconds: 30
  max_memory_mb: 128

network:
  github_api_url: "https://api.github.com"
  default_repo: ""

security:
  allowed_write_paths:
    - "sandbox/agents"
    - "scriptSuggestions"
  disallowed_imports:
    - "os.system"
    - "subprocess"
    - "shutil.rmtree"
    - "importlib"
    - "socket"
  forbidden_calls:
    - "os.system"
    - "subprocess.Popen"
    - "subprocess.run"
    - "eval"
    - "exec"

simulation:
  starting_credit: 10
  reward_per_success: 5
