name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: make lint
      - name: Test
        env:
          OFFLINE_MODE: 'true'
        run: make test
      - name: Require human approval
        if: github.event_name == 'pull_request'
        run: |
          echo "This workflow enforces that PRs require manual review before merging. Configure branch protections in GitHub settings."
